name: flutter_pop_kit
description: "Flutter package designed to simplify the process of displaying customizable popups"
version: 1.0.2
repository: "https://github.com/preciousMzembe/flutter_pop_kit"
license: MIT

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
